title: Git for All

description:
  A quick and short guide to Git aimed primarily at non-developers.  
  Edits, suggestions and reviews are welcome.

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-seo-tag
